language: cpp
compiler: g++

before_script:
  - mkdir build
  - cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make
  
script:
  - cd build && make test
  
os: linux

addons:
  apt:
    packages:
      - cmake
      - g++-4.9