.TH "test/ Directory Reference" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcount_test\&.cpp\fP"
.br
.RI "\fISource file for a test type counting functionality in the \fBcount\&.hpp\fP header file\&. \fP"
.ti -1c
.RI "file \fBeasy_test\&.cpp\fP"
.br
.in -1c
