.TH "Combine::Nth< n, X, Xs >" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Combine::Nth< n, X, Xs > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nth\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCOMBINE_STATIC_ASSERT_TRUE\fP (\fBcount_types\fP< X, Xs\&.\&.\&. >() > n)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<size_t n, typename X, typename\&.\&.\&. Xs>struct Combine::Nth< n, X, Xs >"
A structure template to determine the nth type is the template parameter list\&. 
.SH "Member Function Documentation"
.PP 
.SS "template<size_t n, typename X , typename\&.\&.\&. Xs> \fBCombine::Nth\fP< n, X, Xs >::COMBINE_STATIC_ASSERT_TRUE (\fBcount_types\fP< X, Xs\&.\&.\&. >(), n)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Combine from the source code\&.
