.TH "Combine::Type< X >" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Combine::Type< X > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <type\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<typename X>struct Combine::Type< X >"
A structure template for holding a single type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Combine from the source code\&.
