.TH "Combine::Count_types< X, Xs... >" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Combine::Count_types< X, Xs... > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <count\&.hpp>\fP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static constexpr size_t \fBvalue\fP = 1+Count_types< Xs \&.\&.\&. >::value"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename X, typename\&.\&.\&. Xs>struct Combine::Count_types< X, Xs\&.\&.\&. >"
Iterate speialization of teh data structure template for counting types\&. 
.SH "Member Data Documentation"
.PP 
.SS "template<typename X , typename\&.\&.\&. Xs> constexpr size_t Combine::Count_types< X, Xs\&.\&.\&. >::value = 1+Count_types< Xs \&.\&.\&. >::value\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Combine from the source code\&.
