.TH "Combine::Nth< 0, X, Xs... >" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Combine::Nth< 0, X, Xs... > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nth\&.hpp>\fP
.SH "Detailed Description"
.PP 

.SS "template<template< typename\&.\&.\&. > class Context, typename X, typename Xs>struct Combine::Nth< 0, X, Xs\&.\&.\&. >"
The terminating specialization of the structure template for determining the nth type in a template parameter list\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Combine from the source code\&.
