.TH "combine/count.hpp" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
combine/count.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstddef>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCombine::Count_types<>\fP"
.br
.ti -1c
.RI "struct \fBCombine::Count_types< X, Xs\&.\&.\&. >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCombine\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Xs> constexpr size_t \fBCombine::count_types\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Combine from the source code\&.
