.TH "combine/idx.hpp" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
combine/idx.hpp \- 
.PP
A header file containing definitions of struct templates for building a sequence of nonnegative integer values\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGen_Idx< 0, inidices\&.\&.\&. >\fP"
.br
.ti -1c
.RI "struct \fBGen_Idx< n, indices\&.\&.\&. >\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<size_t n> \fBgen_Idx\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Samuel B\&. Johnson sabjohnso@yahoo.com 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "template<size_t n> gen_Idx ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Combine from the source code\&.
