.TH "combine/type.hpp" 3 "Thu May 21 2015" "Version 0.1" "Combine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
combine/type.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCombine::Type< X >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCombine\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename Stream , typename X > Stream & \fBCombine::operator<<\fP (Stream &s, Type< X >)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Samuel B\&. Johnson 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Combine from the source code\&.
